@ECHO OFF
cls
ECHO.                           
ECHO.                           
ECHO.                           
ECHO.                           
ECHO                        €ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ€
ECHO                        €   DEALER DISC-MAKE MENU  €
ECHO                        €‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹€
ECHO.                           
ECHO.                           
ECHO.                           
ECHO.                           
ECHO     Make an Air/Nitrox only disc in drive A: ................. MAKEAIR
ECHO     Make an Air/Nitrox only disc in drive B: ................. MAKEAIR B:
ECHO.
ECHO     Make a Trimix/Air/Nitrox only disc in drive A: ........... MAKETRI
ECHO     Make a Trimix/Air/Nitrox only disc in drive B: ........... MAKETRI B:
ECHO.                                                    
ECHO     Make a complete Re-Breather/Trimix/Air disc in drive A: .. MAKEREB
ECHO     Make a complete Re-Breather/Trimix/Air disc in drive B: .. MAKEREB B:
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
