Attribute VB_Name = "rbmodule"
Const STARTPATH = "\"
Global DB As Database
Global RS As Recordset
Global RS2 As Recordset
Global RS3 As Recordset
Global RS4 As Recordset
Global SQL As String
Global comfirmDisplay  As String
Global TEMPVERSION  As String
Global tempstartdate As Variant
Global tempfinishdate As Variant
Global profilefound As Integer
Global maxdprofile As Integer
Global tempinterval As String
Global tempmaxd As String
Global tempotu As String
Global tempfinishdate2 As String
Global tempstartdate2 As String
Global tempserialno As String
Global tempduration As String
Global Totalcount As Variant
Global itemheader As String
Global p As Integer
Global displaydefaulted As String
Global itemselected As String
Global displaydefault As String
Global filesource As String
Global tempfilename As String
Global txtdiveid As String
Global tempstring As String
Global tempfilename2 As String
Global tempsysid As String
Global tempstatus As String
Global tempdescend As String
Global templocationfile As String
Global tempsysviewid As String
